package Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import Product.DiscountVisitor;
import Product.ProductFactory;
import application.Model;
import javafx.event.ActionEvent;

public class DiscountPageController {
	@FXML
	private TextField percentage;
	private Model model = new Model();
	// Event Listener on Button.onAction
	@FXML
	public void apply(ActionEvent event) {
		// TODO Autogenerated
		int discount = 0;
		discount = Integer.parseInt(percentage.getText());
		DiscountVisitor d= new DiscountVisitor(discount,discount,discount);
		if(discount >= 0 && discount <=100) {
			for(ProductFactory pf:model.getInventory().getStock()) {
				pf.accept(d);
			}
		}
		model.setData();
		Stage stage = (Stage)percentage.getScene().getWindow();
		stage.close();
	}
}
