package Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import Customer.Card;
import Customer.CreditCard;
import Customer.Customer;
import Customer.PayPal;
import application.Model;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;
import javafx.scene.image.ImageView;

import javafx.scene.control.PasswordField;

import javafx.scene.input.MouseEvent;

public class PaymentPageController {
	@FXML
	private FlowPane CardView;
	@FXML
	private TextField cardName;
	@FXML
	private TextField cardNum;
	@FXML
	private TextField cvv;
	@FXML
	private TextField month;
	@FXML
	private TextField year;
	@FXML
	private Button paybtn;
	@FXML
	private Label alert;
	@FXML
	private ImageView creditCardImg;
	@FXML
	private ImageView paypalImg;
	@FXML
	private FlowPane paypalView;
	@FXML
	private TextField txt;
	@FXML
	private PasswordField pas;
	@FXML
	private Button btnpay2;
	@FXML
	private Label alert2;
	public Customer customer;
	
	// Event Listener on Button[#paybtn].onAction
	@FXML
	public void pay(ActionEvent event) {
		// TODO Autogenerated
		if(cardNum.getText().length() < 12 || cardNum.getText().length() > 12) {
			alert.setText("Non valid card number it must be of 12 number");
			return;
		}
		if(cardName.getText().equals("") || cardNum.getText().equals("") || cvv.getText().equals("") || month.getText().equals("") || year.getText().equals("")) {
			alert.setText("Fill empty fields");
			return;
		}
		customer.SetCard(new Card(cardName.getText(),cardNum.getText(),cvv.getText(),month.getText() + " " + year.getText()));
		customer.getCart().SetPayment(new CreditCard(customer.getCard()));
		alert.setText(customer.getCart().Pay());
		//the customer has payed so empty his cart
		customer.getCart().getCart().clear();
		Stage stage = (Stage)alert.getScene().getWindow();
		stage.setUserData(customer);//return this customer to remove its cart in the controller 
	}
	// Event Listener on ImageView[#creditCardImg].onMouseClicked
	@FXML
	public void CreditCardView(MouseEvent event) {
		// TODO Autogenerated
		CardView.setVisible(true);
		paypalView.setVisible(false);
		creditCardImg.setOpacity(1);
		paypalImg.setOpacity(0.3);
		
	}
	// Event Listener on ImageView[#paypalImg].onMouseClicked
	@FXML
	public void PayPalView(MouseEvent event) {
		// TODO Autogenerated
		CardView.setVisible(false);
		paypalView.setVisible(true);
		creditCardImg.setOpacity(0.3);
		paypalImg.setOpacity(1);

	}
	// Event Listener on Button[#btnpay2].onAction
	@FXML
	public void payP(ActionEvent event) {
		// TODO Autogenerated
		if(txt.getText().trim().equals("") || pas.getText().trim().equals("")) {
			alert2.setText("Fill empty fields");
			return;
		}
		customer.getCart().SetPayment(new PayPal(txt.getText(),pas.getText()));
		alert2.setText(customer.getCart().Pay());
		//the customer has payed so empty his cart
		customer.getCart().getCart().clear();
		Stage stage = (Stage)alert.getScene().getWindow();
		stage.setUserData(customer);//return this customer to remove its cart in the controller 
	}
	public void setCustomer(Customer c) {
		this.customer = c;
	}
}
